package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

public class ReportScreenController {
	@FXML
	private Label grossIncomeLabel;

	

	@FXML
	private AnchorPane mainPane;
	@FXML
	private Button homeButton;
	
	private HomeController callingController;
	private Stage OrderStage;
	

	// Event Listener on Button[#refreshButton].onAction
	@FXML
	
	public void setLabel(String s) {
		grossIncomeLabel.setText(s);
	}
	
	
	public void refreshButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#homeButton].onAction
	@FXML
	public void homeButtonClick(ActionEvent event) {
		if (OrderStage == null) {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/Home.fxml"));
			AnchorPane dialogRoot;
		
			try {
				dialogRoot = (AnchorPane) loader.load();
				Scene dialogScene = new Scene(dialogRoot);
				OrderStage = new Stage();
				OrderStage.setScene(dialogScene);
				OrderStage.setTitle("");
				callingController = (HomeController)loader.getController();
				callingController.setCallingController(this);
				
				
			} catch(IOException e) {
				e.printStackTrace(); }
			OrderStage.show();
			
		}
		OrderStage=null;
		mainPane.getScene().getWindow().hide();
	}
	
	public void setCallingControl(HomeController c) {
		callingController = c;
}
}
